apiVersion: v1
entries:
  ejabberd:
  - apiVersion: v1
    appVersion: "18.03"
    created: "2022-09-20T15:30:52.441823746+02:00"
    description: ejabberd Community Server - Single node
    digest: 4b3849d0b36898d8461e3d07b5bb808f31a2cdfdd10b5e04b832dd0a2fe11a9c
    name: ejabberd
    urls:
    - https://zer0def.github.io/zer0def/charts/ejabberd-0.1.1.tgz
    version: 0.1.1
  patroni:
  - apiVersion: v1
    appVersion: 1.5-p5
    created: "2022-09-20T15:30:52.447798762+02:00"
    dependencies:
    - condition: etcd.deployChart
      name: etcd
      repository: https://charts.helm.sh/incubator
      version: 0.6.2
    - condition: zookeeper.deployChart
      name: zookeeper
      repository: https://charts.helm.sh/incubator
      version: 1.0.0
    - condition: consul.deployChart
      name: consul
      repository: https://charts.helm.sh/stable
      version: 3.6.1
    digest: b740254a99e97ce787c6afd6c62403f92fe9d6354680f0b933d227ba4ab2f831
    home: https://github.com/zalando/patroni
    name: patroni
    sources:
    - https://github.com/zalando/patroni
    - https://github.com/zalando/spilo
    urls:
    - https://zer0def.github.io/zer0def/charts/patroni-0.16.3.tgz
    version: 0.16.3
  prosody:
  - apiVersion: v1
    appVersion: 0.9.12
    created: "2022-09-20T15:30:52.448983577+02:00"
    description: A Helm chart for Kubernetes
    digest: 1b8a8866ce78b94702432a923e2bfda205a2e381e8d9fd59067c57669b530c4d
    name: prosody
    urls:
    - https://zer0def.github.io/zer0def/charts/prosody-0.1.0.tgz
    version: 0.1.0
  redpanda:
  - apiVersion: v1
    appVersion: latest
    created: "2022-09-20T15:30:52.450150036+02:00"
    deprecated: true
    description: Redpanda is the real-time engine for modern apps.
    digest: 49d2975b1d062fbea41ea1c7f1184dac27cabac103f7dfa4bb598f410f73b3c8
    name: redpanda
    sources:
    - https://github.com/vectorizedio/helm-charts
    type: application
    urls:
    - https://zer0def.github.io/zer0def/charts/redpanda-1.0.6.tgz
    version: 1.0.6
  seaweedfs:
  - apiVersion: v1
    appVersion: "3.27"
    created: "2022-09-20T15:30:52.454440577+02:00"
    description: SeaweedFS
    digest: dd34e0ce8882b4fa516483f102e23afdbb703875f33ef330059afe8ed8f0d858
    name: seaweedfs
    urls:
    - https://zer0def.github.io/zer0def/charts/seaweedfs-3.27.tgz
    version: "3.27"
  thanos:
  - apiVersion: v1
    appVersion: 0.17.1
    created: "2022-09-20T15:30:52.459398175+02:00"
    description: Thanos is a set of components that can be composed into a highly
      available metric system with unlimited storage capacity, which can be added
      seamlessly on top of existing Prometheus deployments.
    digest: 44ca86f48339581ee0fcb8d2f70b644df230e3453a99fbbb12a33337dc3a30af
    icon: https://raw.githubusercontent.com/thanos-io/thanos/master/docs/img/Thanos-logo_fullmedium.png
    keywords:
    - thanos
    - prometheus
    - metrics
    maintainers:
    - email: info@banzaicloud.com
      name: Banzai Cloud
    name: thanos
    sources:
    - https://github.com/thanos-io/thanos
    - https://github.com/banzaicloud/banzai-charts/tree/master/thanos
    urls:
    - https://zer0def.github.io/zer0def/charts/thanos-0.4.6.tgz
    version: 0.4.6
generated: "2022-09-20T15:30:52.440571114+02:00"
