apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "prosody.fullname" . }}
  labels:
    app: {{ template "prosody.name" . }}
    chart: {{ template "prosody.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  prosody.cfg.lua: {{ tpl (.Files.Get "files/prosody.cfg.lua.tpl") . | b64enc }}
