apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "ejabberd.fullname" . }}
  labels:
    app: {{ template "ejabberd.name" . }}
    chart: {{ template "ejabberd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  # need to fix this randAlphaNum to be static or external
  .erlang.cookie: {{ randAlphaNum 32 | b64enc | quote }}
  cluster.sh: {{ .Files.Get "files/cluster.sh" | b64enc }}
  ejabberdctl.cfg: {{ tpl (.Files.Get "files/ejabberdctl.cfg.tpl") . | b64enc }}
  ejabberd.yml: {{ if .Values.configOverride }}{{ toYaml .Values.configOverride | b64enc }}{{ else }}{{ tpl (.Files.Get "files/ejabberd.yml.tpl") . | b64enc }}{{ end }}
