{{/*
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "patroni.fullname" . }}-initdb-conf-template
  labels:
    app: {{ template "patroni.name" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  postgresql.conf.sample: |
    {{ .Files.Get "files/postgresql.conf.sample" | nindent 4 }}
---
*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "patroni.fullname" . }}
  labels:
    app: {{ template "patroni.fullname" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  hashedname: {{ template "patroni.hashedname" $ }}
{{- if .Values.metrics.postgresql.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "patroni.fullname" . }}-pgsql-exporter-queries
  labels:
    app: {{ template "patroni.name" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yaml: |
{{ printf .Values.metrics.postgresql.queries | indent 4 }}
{{- end }}
