apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ejabberd.fullname" . }}
  labels:
    app: {{ template "ejabberd.name" . }}
    chart: {{ template "ejabberd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  cluster.sh: {{ .Files.Get "files/cluster.sh" | nindent 4 }}
