{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ejabberd.fullname" . }}
  labels:
    app: {{ template "ejabberd.name" . }}
    chart: {{ template "ejabberd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: {{ $.Values.ingress.path }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ template "ejabberd.fullname" $ }}
            port:
              name: http
  {{- end }}
{{- end }}
