# cluster-major-version-specific service
apiVersion: v1
kind: Service
metadata:
  name: {{ template "patroni.hashedname" . }}
  labels:
    app: {{ template "patroni.fullname" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ template "patroni.hashedname" . }}
    heritage: {{ .Release.Service }}
    component: pgsql
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
---
# headless service to manage Endpoints object whose annotations serve as cluster state
apiVersion: v1
kind: Service
metadata:
  name: {{ template "patroni.hashedname" . }}-config
  labels:
    app: {{ template "patroni.fullname" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ template "patroni.hashedname" . }}
    heritage: {{ .Release.Service }}
    component: pgsql
spec:
  type: ClusterIP
  clusterIP: None
